'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class adjustment
    Public Property Id As Integer
    Public Property ModifyDate As Date
    Public Property Quantity As Integer
    Public Property ModifyBy As String
    Public Property stockId As Integer

    Public Overridable Property stock As stock

End Class
