'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class agent
    Public Property Id As Integer
    Public Property Name As String
    Public Property Address As String
    Public Property Contact As String
    Public Property Tin As String
    Public Property ModifyBy As String
    Public Property ModifyDate As Nullable(Of Date)
    Public Property Active As Boolean

    Public Overridable Property customers As ICollection(Of customer) = New HashSet(Of customer)
    Public Overridable Property salesorders As ICollection(Of salesorder) = New HashSet(Of salesorder)
    Public Overridable Property salesreturns As ICollection(Of salesreturn) = New HashSet(Of salesreturn)

End Class
