'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class category
    Public Property Id As Integer
    Public Property Name As String
    Public Property Active As Boolean
    Public Property ModifyBy As String
    Public Property ModifyDate As Nullable(Of Date)

    Public Overridable Property stocks As ICollection(Of stock) = New HashSet(Of stock)

End Class
