'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class collectionorderitem
    Public Property Id As Integer
    Public Property salesorderId As Integer
    Public Property Amount As Double
    Public Property customercollectionId As Integer
    Public Property BalanceGot As Double

    Public Overridable Property customercollection As customercollection
    Public Overridable Property salesorder As salesorder

End Class
