'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class counter
    Public Property Id As Integer
    Public Property Name As String
    Public Property Count As Integer
    Public Property Prefix As String
    Public Property Owner As String
    Public Property Active As Boolean

End Class
