'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class customer
    Public Property Id As Integer
    Public Property Name As String
    Public Property Address As String
    Public Property Contact As String
    Public Property Fax As String
    Public Property Tin As String
    Public Property Commission As Nullable(Of Double)
    Public Property AgentId As Nullable(Of Integer)
    Public Property ModifyBy As String
    Public Property ModifyDate As Nullable(Of Date)
    Public Property Active As Boolean

    Public Overridable Property agent As agent
    Public Overridable Property customercollections As ICollection(Of customercollection) = New HashSet(Of customercollection)
    Public Overridable Property salesorders As ICollection(Of salesorder) = New HashSet(Of salesorder)
    Public Overridable Property salesreturns As ICollection(Of salesreturn) = New HashSet(Of salesreturn)

End Class
