'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class DatabaseContext
    Inherits DbContext

    Public Sub New(ByVal connectionStringName As String)
        MyBase.New(connectionStringName)
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Property activities() As DbSet(Of activity)
    Public Property agents() As DbSet(Of agent)
    Public Property categories() As DbSet(Of category)
    Public Property collectioncheckitems() As DbSet(Of collectioncheckitem)
    Public Property collectionorderitems() As DbSet(Of collectionorderitem)
    Public Property counters() As DbSet(Of counter)
    Public Property customercollections() As DbSet(Of customercollection)
    Public Property customers() As DbSet(Of customer)
    Public Property paymentcheckitems() As DbSet(Of paymentcheckitem)
    Public Property paymentorderitems() As DbSet(Of paymentorderitem)
    Public Property purchaseorderitems() As DbSet(Of purchaseorderitem)
    Public Property purchaseorders() As DbSet(Of purchaseorder)
    Public Property purchasereturnitems() As DbSet(Of purchasereturnitem)
    Public Property purchasereturns() As DbSet(Of purchasereturn)
    Public Property salesorderitems() As DbSet(Of salesorderitem)
    Public Property salesorders() As DbSet(Of salesorder)
    Public Property salesreturnitems() As DbSet(Of salesreturnitem)
    Public Property salesreturns() As DbSet(Of salesreturn)
    Public Property stocks() As DbSet(Of stock)
    Public Property supplierpayments() As DbSet(Of supplierpayment)
    Public Property suppliers() As DbSet(Of supplier)
    Public Property units() As DbSet(Of unit)
    Public Property users() As DbSet(Of user)
    Public Property adjustments() As DbSet(Of adjustment)

End Class
