'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class paymentcheckitem
    Public Property Id As Integer
    Public Property DocumentNo As String
    Public Property [Date] As Date
    Public Property Amount As Double
    Public Property supplierpaymentId As Integer

    Public Overridable Property supplierpayment As supplierpayment

End Class
