'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class purchaseorder
    Public Property Id As Integer
    Public Property DocumentNo As String
    Public Property [Date] As Date
    Public Property Remarks As String
    Public Property PostedDate As Nullable(Of Date)
    Public Property TotalAmount As Double
    Public Property supplierId As Integer
    Public Property ModifyBy As String
    Public Property ModifyDate As Nullable(Of Date)
    Public Property TotalPaid As Double
    Public Property TotalReturned As Double
    Public Property Discount1 As Double
    Public Property Discount2 As Double
    Public Property Discount3 As Double

    Public Overridable Property paymentorderitems As ICollection(Of paymentorderitem) = New HashSet(Of paymentorderitem)
    Public Overridable Property purchaseorderitems As ICollection(Of purchaseorderitem) = New HashSet(Of purchaseorderitem)
    Public Overridable Property supplier As supplier

    Public Function getBalance() As Double
        Return FormatNumber(TotalAmount - (TotalPaid + TotalReturned), 2)
    End Function

    Public Function getTotalReturnedFromItems() As Double
        Dim returnedTotal As Double = 0
        For Each item In purchaseorderitems
            returnedTotal += item.getStockNetPrice * item.QuantityReturned
        Next
        Return FormatNumber(returnedTotal, 2)
    End Function

End Class
