'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class purchasereturn
    Public Property Id As Integer
    Public Property DocumentNo As String
    Public Property [Date] As Date
    Public Property Remarks As String
    Public Property PostedDate As Nullable(Of Date)
    Public Property TotalAmount As Double
    Public Property ModifyBy As String
    Public Property ModifyDate As Date
    Public Property supplierId As Integer

    Public Overridable Property purchasereturnitems As ICollection(Of purchasereturnitem) = New HashSet(Of purchasereturnitem)
    Public Overridable Property supplier As supplier

End Class
