'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class salesreturnitem
    Public Property Id As Integer
    Public Property Quantity As Short
    Public Property Price As Double
    Public Property Discount1 As Double
    Public Property Discount2 As Double
    Public Property stockId As Integer
    Public Property salesreturnId As Integer

    Public Overridable Property salesreturn As salesreturn
    Public Overridable Property stock As stock

End Class
