'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class salesorder
    Public Property Id As Integer
    Public Property DocumentNo As String
    Public Property [Date] As Date
    Public Property PostedDate As Nullable(Of Date)
    Public Property Remarks As String
    Public Property Discount1 As Double
    Public Property Discount2 As Double
    Public Property TotalAmount As Double
    Public Property ModifyBy As String
    Public Property ModifyDate As Date
    Public Property customerId As Integer
    Public Property agentId As Integer
    Public Property TotalPaid As Double
    Public Property TotalReturned As Double

    Public Overridable Property agent As agent
    Public Overridable Property collectionorderitems As ICollection(Of collectionorderitem) = New HashSet(Of collectionorderitem)
    Public Overridable Property customer As customer
    Public Overridable Property salesorderitems As ICollection(Of salesorderitem) = New HashSet(Of salesorderitem)

    Public Function getBalance() As Double
        Dim balance As Double = TotalAmount - (TotalPaid + TotalReturned)
        Return FormatNumber(CDbl(balance), 2)
    End Function

    Public Function getTotalReturnedFromItems() As Double
        Dim returnedTotal As Double = 0
        For Each item In salesorderitems
            returnedTotal += item.getStockNetPrice * item.QuantityReturned
        Next
        Return FormatNumber(returnedTotal, 2)
    End Function

End Class
