'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class salesreturn
    Public Property Id As Integer
    Public Property DocumentNo As String
    Public Property [Date] As Date
    Public Property Remarks As String
    Public Property PostedDate As Nullable(Of Date)
    Public Property TotalAmount As Double
    Public Property ModifyBy As String
    Public Property ModifyDate As Date
    Public Property customerId As Integer
    Public Property agentId As Integer

    Public Overridable Property agent As agent
    Public Overridable Property customer As customer
    Public Overridable Property salesreturnitems As ICollection(Of salesreturnitem) = New HashSet(Of salesreturnitem)

End Class
