'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class salesorderitem
    Public Property Id As Integer
    Public Property Discount1 As Double
    Public Property Discount2 As Double
    Public Property Quantity As Integer
    Public Property Price As Double
    Public Property stockId As Integer
    Public Property salesorderId As Integer
    Public Property QuantityReturned As Integer

    Public Overridable Property stock As stock
    Public Overridable Property salesorder As salesorder

    Public Function getStockNetPrice() As Double
        Dim netPrice As Double
        netPrice = Price
        netPrice = netPrice - (netPrice * (Discount1 / 100))
        netPrice = netPrice - (netPrice * (Discount2 / 100))
        Return FormatNumber(netPrice, 2)
    End Function

    Public Function getRemainingQuantity() As Integer
        Return Quantity - QuantityReturned
    End Function

End Class
