'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class stock
    Public Property Id As Integer
    Public Property Name As String
    Public Property Description As String
    Public Property Cost As Nullable(Of Double)
    Public Property RetailPrice As Double
    Public Property WholesalePrice As Double
    Public Property QtyOnHand As Integer
    Public Property UnitId As Nullable(Of Integer)
    Public Property CategoryId As Nullable(Of Integer)
    Public Property ModifyBy As String
    Public Property ModifyDate As Nullable(Of Date)
    Public Property Active As Boolean

    Public Overridable Property adjustments As ICollection(Of adjustment) = New HashSet(Of adjustment)
    Public Overridable Property category As category
    Public Overridable Property purchaseorderitems As ICollection(Of purchaseorderitem) = New HashSet(Of purchaseorderitem)
    Public Overridable Property purchasereturnitems As ICollection(Of purchasereturnitem) = New HashSet(Of purchasereturnitem)
    Public Overridable Property salesorderitems As ICollection(Of salesorderitem) = New HashSet(Of salesorderitem)
    Public Overridable Property salesreturnitems As ICollection(Of salesreturnitem) = New HashSet(Of salesreturnitem)
    Public Overridable Property unit As unit
    Public Overridable Property customerprices As ICollection(Of customerprice) = New HashSet(Of customerprice)

End Class
