'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class supplierpayment
    Public Property Id As Integer
    Public Property [Date] As Date
    Public Property PostedDate As Nullable(Of Date)
    Public Property Remarks As String
    Public Property TotalCheck As Double
    Public Property TotalPaid As Double
    Public Property ModifyBy As String
    Public Property ModifyDate As Date
    Public Property Bank As String
    Public Property supplierId As Integer
    Public Property DocumentNo As String

    Public Overridable Property paymentcheckitems As ICollection(Of paymentcheckitem) = New HashSet(Of paymentcheckitem)
    Public Overridable Property paymentorderitems As ICollection(Of paymentorderitem) = New HashSet(Of paymentorderitem)
    Public Overridable Property supplier As supplier

End Class
